### ISSUE TITLE
PyPI install fails without first updating pip

### ISSUE THREAD

**Issue by DanielSank** [quantumlib/OpenFermion#38]
I made a virtualenv and did this

```
pip install --pre openfermion
```

and got

```
...
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /usr/local/google/home/danielsank/.virtualenvs/openfermion/build/h5py
Traceback (most recent call last):
  File "/usr/local/google/home/danielsank/.virtualenvs/openfermion/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/google/home/danielsank/.virtualenvs/openfermion/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/local/google/home/danielsank/.virtualenvs/openfermion/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

```

This was with python 2.7.6 and pip 1.5.4.

**Comment by DanielSank** [comment]
Aha, upgrading to pip 9.0.1 fixed the problem. I should have known as I've seen this problem before. It's not this project's job to fix pip, but this problem happens *all* the time so we might want to add something to the README.

**Comment by DanielSank** [comment]
My recommended installation for people who use virtualenv would be (after activating your virtualenv):

```
pip install -U pip
pip install --pre openfermion
```
